config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'mcp_contact' => 'static_pages#contact'
  get 'news' => 'static_pages#news'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  resources :users
  resources :account_activations, only: [:edit] # az aktivalasokhoz
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :notes
  get "notes/:id/archive/" => "notes#archive", as: "note_archive"
  get "notes/:id/activate/" => "notes#activate", as: "note_activate"
  resources :contacts

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence:true
  validates :title, presence:true, length: { maximum: 255 }
  validates :content, presence: true, length: { maximum: 10000 }
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :logged_in_user, only: [:show, :create, :edit, :update, :destroy]
  
  def show
    @user = current_user
    @notes = @user.notes.paginate(page: params[:page])
    @note = Note.find_by(id: params[:id])    
    highlight(@note, session[:search_keywords]) if @note && session[:search_keywords]
  end
  
  def new
    @new_note = Note.new
    redirect_to root_url if not logged_in?
  end
  
  def create
    @new_note = current_user.notes.build(note_params)
    if @new_note.save
      flash[:success]="Note created"
      redirect_to notes_path
    else
      render 'new'
    end
  end
  
  def edit
    @edit_note = Note.find_by(id: params[:id])
    if @edit_note.archived
      redirect_to notes_path
    end
  end
  
  def archive
    @archive_note = Note.find_by(id: params[:id])
    @archive_note.update_attribute( :archived, 'true')
    redirect_to notes_path
  end
  
  def activate
    @archive_note = Note.find_by(id: params[:id])
    @archive_note.update_attribute( :archived, 'false')
    redirect_to notes_path
  end
    
  def update
    @edit_note = Note.find_by(id: params[:id])
    if @edit_note.update_attributes(note_params)
      flash[:success]="Note successfully edited."
      redirect_to @edit_note
    else
      render 'edit'
    end
  end
  
  def destroy
    note = Note.find_by(id: params[:id])
    note.destroy
    flash[:success]="Note deleted. "
    redirect_to notes_path
  end
  
  def index
    if logged_in?
      @user = current_user
      session[:show_archived_notes]||='false'

      if params[:show_archived_notes] 
	session[:show_archived_notes]=params[:show_archived_notes]
      end
      
      if params[:search_keywords]
	session[:search_keywords]=params[:search_keywords]
      else
	session.delete(:search_keywords)
      end
      
      @active_notes = @user.notes.where(archived: false)
				  .where("content LIKE ? OR title LIKE ?", 
				         "%"+session[:search_keywords].to_s+"%", 
				         "%"+session[:search_keywords].to_s+"%")
				  .paginate(page: params[:page])
      if session[:show_archived_notes]=='true'        
	@archived_notes = @user.notes.where(archived: true)
				      .where("content LIKE ? OR title LIKE ?", 
				             "%"+session[:search_keywords].to_s+"%", 
				             "%"+session[:search_keywords].to_s+"%")
				      .paginate(page: params[:page])
      end
      if session[:search_keywords]
	@active_notes.each do |note|
	  #note.title = note.title.gsub session[:search_keywords], "<b>" + session[:search_keywords] + "</b>"
	  #note.content = note.content.gsub(session[:search_keywords], "<b>" + session[:search_keywords] + "</b>")
	  highlight(note, session[:search_keywords])
	end if @active_notes
	@archived_notes.each do |note|
	  #note.title = note.title.gsub session[:search_keywords], "<b>" + session[:search_keywords] + "</b>"
	  #note.content = note.content.gsub(session[:search_keywords], "<b>" + session[:search_keywords] + "</b>")
	  highlight(note, session[:search_keywords])
	end if @archived_notes
      end
    else
    redirect_to root_url
    end
  end
  
  private
    def highlight(target, part)
      target.title = target.title.gsub part, '<b>' + part + '</b>'
      target.content = target.content.gsub part, '<b>' + part + '</b>'
    end
  
    def note_params
      params.require(:note).permit(:title, :content, :archived)
    end
    
    def correct_user
      @note = current_user.notes.find_by(id: params[:id])
      redirect_to root_url if @note.nil
    end
    
    def search_results
      keywords = "%"+params[:search_keywords]+"%"
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_archive_note.erb
<% if object.archived %>
  <%= link_to "Activate", note_activate_path(object), class: "btn" %>
<% else %>
  <%= link_to "Archive", note_archive_path(object), class: "btn" %>
<% end %> 

app/views/notes/_archive_note_button.erb
<% if object.archived %>
  <%= link_to "Activate", note_activate_path(object), class: "btn" %>
<% else %>
  <%= link_to "Archive", note_archive_path(object), class: "btn" %>
<% end %> 

app/views/notes/_buttons_show.erb
<% if object.archived %>
  <%= link_to "Activate", note_activate_path(object), class: "btn btn-xs" %>
<% else %>
  <%= link_to "Archive", note_archive_path(object), class: "btn btn-xs" %>
<% end %> 

<%= link_to "Edit", edit_note_path(object), class: "btn btn-xs" if not object.archived %>

<%= link_to "Delete", object, method: :delete, class: "btn btn-xs", data: {confirm: "Are you sure?"} %>

app/views/notes/_note.html.erb
<li id="notes-<%= note.id  %>">
  <div class="col-md-5">
    <% if not note.title  %>
      <%= link_to "No title" , note %>
    <% else %>
      <%= link_to simple_format(note.title) , note %>
    <% end %>
  </div>
  <div class="col-md-3">
    <%= link_to "show", note_path(note), class: "btn btn-primary btn-xs" %>
    <%= render 'buttons_show', object: note %>
  </div>
  <div class="col-md-4">
    <div class="timestamp">(posted: <%= time_ago_in_words(note.created_at) %> ago,
			    updated: <%= time_ago_in_words(note.updated_at) %>)</div>
  </div>
</li>
 

app/views/notes/edit.html.erb
<% provide :title, "Edit note" %>
<h1>Update note</h1>
<div class="row">
  <div class="col-md-12">
    <%= form_for @edit_note do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="field">
	<%= f.text_field :title, maxlength: 255 %>
      </div>
      <div class="field">
	<%= f.text_area :content, rows: 12, maxlength: 10000 %>
      </div>
      <%= f.submit "Update", class: "btn btn-primary" %>
      <div class="cancel">
	<%= link_to "Cancel, return to note", @edit_note, class: "btn" %>
      </div>
    <% end %>
</div>
 

app/views/notes/index.html.erb
<%= provide :title, "Notes" %>

<div class="col-md-12">
    <!-- create note button -->
    <%=link_to "Create new note", new_note_path, class: "btn btn-primary" %>
        
    <% if session[:show_archived_notes] && session[:show_archived_notes]=='true' %>
      <%= link_to "Hide archived notes", notes_path(show_archived_notes: false, search_keywords: params[:search_keywords]), class: "btn" %>
    <% else %>
      <%= link_to "Show archived notes", notes_path(show_archived_notes: true, search_keywords: params[:search_keywords]), class: "btn" %>
    <% end %>
    
    <% if params[:search_keywords]%>
      <%=link_to "All notes (search reset)", notes_path, class: "btn" %>
    <% end %>
</div>

<div class="col-md-12">
  <section>
    <%= form_tag notes_path, method: "get" do %>
      <%= text_field_tag :search_keywords, nil, placeholder: "Search keywords " + params[:search_keywords].to_s, class: "col-md-9" %>
      <%= submit_tag "SEARCH NOTES", class: "btn btn-default", class: "col-md-2 btn-default" %>
    <% end %>
  </section>
  <section>
    <h3> Active notes found: (<%= @active_notes ? @active_notes.count : 0 %>) </h3>
    <% if @active_notes %>
      <%= will_paginate @active_notes if @active_notes.count>30 %>
      <ol class="notes">
	<%= render @active_notes %>
      </ol>
      <%= will_paginate @active_notes if @active_notes.count>30%>
    <% end %>
    <% if session[:show_archived_notes]=='true' %>
      <h3> Archived notes found: (<%= @archived_notes ? @archived_notes.count : 0 %>)</h3>
      <% if @archived_notes %>
	<%= will_paginate @archived_notes if @archived_notes.count>30 %>
	<ol class="notes">
	  <%= render @archived_notes %>
	</ol>
	<%= will_paginate @archived_notes if @archived_notes.count>30 %>
      <% end %>
    <% end %>
  </div>
  </section>
</aside>

app/views/notes/new.html.erb
<%= provide :title, "New nNotes" %>

<div class="row">
  <div class="col-md-12">
    <%= form_for @new_note do |f| %> 
      <%= render 'shared/error_messages', object: f.object %>
      <div class="field">
	<%= f.text_field :title,  maxlength: 255, placeholder: "Note title..." %>
      </div>
      <div class="field">
	<%= f.text_area :content, rows: 8, maxlength: 10000, placeholder: "Compose new note..." %>
      </div>
      <%= f.submit "Save", class: "btn btn-primary" %>
    <% end %>
  </div>

</div>
 

app/views/notes/show.html.erb
<%= provide(:title, "Note") %>

<div class="col-md-12">
  <%= link_to "Back to notes", notes_path(show_archived_notes: session[:show_archived_notes], search_keywords: session[:search_keywords]), class: "btn btn-primary" %>
  <% if current_user?(@note.user) %>
    <%= render 'buttons_show', object: @note %>
  <% end %>
</div>

<div class="notes">
  <div class="timestamp">Posted: <%= time_ago_in_words(@note.created_at) %> ago
   /  Last updated: <%= time_ago_in_words(@note.updated_at) %> ago</div>
  <h4><%= simple_format @note.title %></h4>
  <div class="show">
    <%= simple_format @note.content %>
  </div>
</div>

<div class="col-md-12">
   <%= link_to "Back to notes", notes_path(show_archived_notes: session[:show_archived_notes], search_keywords: session[:search_keywords]), class: "btn btn-primary" %>
  <% if current_user?(@note.user) %>
    <%= render 'buttons_show', object: @note %>
  <% end %>
</div>