config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'mcp_contact' => 'static_pages#contact'
  get 'news' => 'static_pages#news'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  resources :users
  resources :account_activations, only: [:edit] # az aktivalasokhoz
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :notes
  get "notes/:id/archive/" => "notes#archive", as: "note_archive"
  get "notes/:id/activate/" => "notes#activate", as: "note_activate"
  resources :contacts

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :user
  validates :name, presence: true, length: { maximum: 50 }
  validates :memo, length: { maximum: 50 }
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :logged_in_user
  
  def new
    @new_contact = Contact.new
    redirect_to root_url if not logged_in?
  end
  
  def create
    @new_contact = current_user.contacts.build(contact_params)
    if @new_contact.save
      flash[:success] = "Contact created"
      redirect_to contacts_path
    else
      render 'new'
    end
  end
  
  def show
    @user = current_user
    @contact = Contact.find_by(id: params[:id])
  end
  
  def index
    if logged_in?
      @user = current_user
      @contacts = @user.contacts.paginate(page: params[:page])
    else
      redirect_to root_url
    end
  end
  
  def edit
    @edit_contact = Contact.find_by(id: params[:id])
  end
  
  def update
    @edit_contact = Contact.find_by(id: params[:id])
    if @edit_contact.update_attributes(contact_params)
      flash[:success]="Contact edited"
      redirect_to @edit_contact
    else
      render 'edit'
    end
  end
  
  def destroy
    contact = Contact.find_by(id: params[:id])
    contact.destroy
    flash[:success]="Contact deleted"
    redirect_to contacts_path
  end
  
  private
  
    def contact_params
      params.require(:contact).permit(:name, :memo)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_buttons_show.erb
<%= link_to "Edit", edit_contact_path(object), class: "btn btn-xs" %>

<%= link_to "Delete", object, method: :delete, class: "btn btn-xs", data: {confirm: "Are you sure?"} %>

app/views/contacts/_contact.html.erb
<li id="contacts-<%= contact.id  %>">
  <div class="col-md-4">
    <%= link_to simple_format(contact.name) , contact %>
  </div>
  <div class="col-md-4">
    <%= contact.memo %>
  </div>
  <div class="col-md-4">
    <div class="timestamp">(Last updated: <%= time_ago_in_words(contact.updated_at) %>)</div>
  </div>
</li>
 
 

app/views/contacts/edit.html.erb
<%= provide :title, "New Contact" %>

<div class="row">
  <div class="col-md-12">
    <%= form_for @edit_contact do |f| %> 
      <%= render 'shared/error_messages', object: f.object %>
      <div class="field">
	<%= f.text_field :name,  maxlength: 50, placeholder: "Contact name..." %>
      </div>
      <div class="field">
	<%= f.text_field :memo, maxlength: 50, placeholder: "Contact memo..." %>
      </div>
      <%= f.submit "Save", class: "btn btn-primary" %>
    <% end %>
    <div class="cancel">
      <%= link_to "Cancel, return to contact", @edit_contact, class: "btn" %>
    </div>
  </div>

</div>
 
 

app/views/contacts/index.html.erb
<%= provide :title, "Contacts" %>

<h1> Contacts </h1>

<div class="col-md-12">
    <!-- create contact button -->
    <%=link_to "Create new contact", new_contact_path, class: "btn btn-primary" %>
    <section>
    <%= form_tag contacts_path, method: "get" do %>
      <%= text_field_tag :search_contacts, nil, placeholder: "Search contacts " + params[:search_keywords].to_s, class: "col-md-9" %>
      <%= submit_tag "SEARCH CONTACTS", class: "btn btn-default", class: "col-md-2 btn-default" %>
    <% end %>
  </section>
  <section>
    <h3>Contacts found: <%= @contacts? @contacts.count : 0 %> </h3>
    <% if @contacts %>
      <%= will_paginate @contacts if @contacts.count > WillPaginate.per_page %>
      <ol class="contacts">
	<%= render @contacts %>
      </ol>
      <%= will_paginate @contacts if @contacts.count > WillPaginate.per_page %>
    <% end %>
  </section>
</div>

app/views/contacts/new.html.erb
<%= provide :title, "New Contact" %>

<div class="row">
  <div class="col-md-12">
    <%= form_for @new_contact do |f| %> 
      <%= render 'shared/error_messages', object: f.object %>
      <div class="field">
	<%= f.text_field :name,  maxlength: 50, placeholder: "Contact name..." %>
      </div>
      <div class="field">
	<%= f.text_field :memo, maxlength: 50, placeholder: "Contact memo..." %>
      </div>
      <%= f.submit "Save", class: "btn btn-primary" %>
    <% end %>
  </div>

</div>
 
 

app/views/contacts/show.html.erb
<%= provide :title, "Show contact" %> 

<div class="contacts">
  <section>
    <%= link_to "Back to contacts", contacts_path, class: "btn btn-primary" %>
    <% if current_user?(@contact.user) %>
      <%= render 'buttons_show', object: @contact %>
    <% end %>
  </section>
  <h3><%= @contact.name %></h3>
  <section>
    <div class="col-md-6"><div class="memo"><%= @contact.memo %></div></div>
    <div class="col-md-3"><div class="timestamp">(Last updated: <%= time_ago_in_words(@contact.updated_at) %>)</div></div>
  </section>
  <section>
    <h4>E-mail adress(es)</h4>
  </section>
  <section>
    <h4>Phone numbers</h4>
  </section>
  <section>
    <h4>Web</h4>
  </section>
  <section>
    <h4>Social media</h4>
  </section>
  <section>
    <h4>Other</h4>
  </section>
</div>