config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  get 'about' => 'static_pages#about'
  get 'mcp_contact' => 'static_pages#contact'
  get 'news' => 'static_pages#news'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'signup' => 'users#new'
  resources :users
  resources :account_activations, only: [:edit] # az aktivalasokhoz
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :notes
  get "notes/:id/archive/" => "notes#archive", as: "note_archive"
  get "notes/:id/activate/" => "notes#activate", as: "note_activate"
  resources :contacts

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    by me.
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", "#" %></li>
      <li><%= link_to "Contact", "#" %></li>
      <li><%= link_to "News", "#" %></li>
    </ul>
  </nav>
</footer>

<%= debug(params) if Rails.env.development? %>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
  <%= link_to "My Control Panel", root_path, id:"logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%=link_to "Home", root_path %></li>
        <% if logged_in? %>
	  <li><%=link_to "Tasks", "#" %></li>
	  <li><%=link_to "Projects", "#" %></li>
	  <li class=dropdown>
	    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Resources<b class="caret"></b></a>
	    <ul class="dropdown-menu">
	      <li><%= link_to "Images", "#" %></li>
	      <li><%= link_to "Documents", "#" %></li>
	      <li><%= link_to "Contacts", contacts_path %></li>
	    </ul>
	  </li>
	  <li><%=link_to "Finances", "#" %></li>
	  <li><%=link_to "Notes", notes_path %></li>
	  <li><%=link_to "Messages", "#" %></li>
	  <% if current_user.admin? %>
	    <li><%= link_to "Users", users_path %></li>
	  <% end %>
	  <li class=dropdown>
	    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
	    <ul class="dropdown-menu">
	      <li><%= link_to "Profile", current_user %></li>
	      <li><%= link_to "Settings", edit_user_path(current_user) %></li>
	      <li class="divider"></li>
	      <li><%= link_to "Log Out", logout_path, method: "delete" %></li>
	    </ul>
	  </li>
        <% else %>
	  <li><%=link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!-- [IF lt IE 9]
  <script src="/cdnjs.cloudflare.com/ajax/lib/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield( :title)) %> </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  
  <%= render 'layouts/header' %>
  
  <div class="container">
      <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{ message_type }") %>
    <% end %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </div>
  
</body>
</html>